version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"